version: '3'

services:
  dycast-web:
    image: dycast-web
    build:
      context: ./dycast-web
      dockerfile: Dockerfile
    environment:
    - MAPBOX_ACCESS_TOKEN=
    - DYCAST_DB_HOST=
    - DYCAST_DB_USER=
    - DYCAST_DB_PASSWORD=
